# Generated by Django 3.2.6 on 2021-10-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_title',
            field=models.TextField(default='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='image_path',
            field=models.TextField(default='/images/forinfo/default.png', null=True),
        ),
    ]
